### PR TITLE
Not actually a pull-request. Demo of possible live figures implementation

### PR DESCRIPTION
**Pull request by JerryI**
Hi @jacopouggeri,
Sorry for the late reply. I tried to poke a problem of a static graphics in your new digital paper format using JS

The demo is available by the [link](https://jerryi.github.io/fern-demo/wljs-test/)

The idea is to use [WLJS Interpreter](https://jerryi.github.io/wljs-docs/docs/interpreter/intro) for drawing graphics. This is a freeware implementation of a minimal Wolfram Language core running in the browser. It is still a big question, what is a proper format for 2D and 3D figures , but so far I could not find the solution, that can cover all needs (at least for a scientist), therefore I tried in with JS and WL. Using a plain JS is a pain for sure, therefore I though it would need something else to make it easier.

In this demo each figures is stored as `json` file with a list of primitives like `Line`, `Point`, `RGBColor`, that describes the output image. The interpreter goes through them and make an interactive SVG / WebGL (in a case of 3D plots) image. 

The advantage of it, that the code can be generated by the "hight-order" functions using freeware Wolfram Engine (as a did actually) for instance based on the input data (can be CSV or whater). This process can also be automatized using GitHub actions with some limitations, I believe. 

So... I am quite curious to head your opinion on that. :)

If it does not fit your ideas about Fern, it is also fine. 

Cheers,
Kirill

### CODE REVIEW

**Comment by jacopouggeri** [comment]
Dear @JerryI,
First of all, thanks for getting interested!

I will check this more in detail later, but from the first look I gave at the demo it looks fanstastic! To be fair, what fern is going to be is a bit up in the air right now and I was hoping some discussion would help in that regard. What you did certainly demonstrates the power of using web design tools for fern, as it can allow for the inclusion of dynamic graphics and animations, which is one of the key strengths I envisioned for fern. After all, if most papers are read online or digitally nowadays, why should we stick with only text and images? Where appropriate, other kinds of media would only enhance the academic content, and it would be a shame to ignore this possibility.

I will get back at you after I've given this a better look.
Thanks again,
Cheers,
Jacopo

**Comment by JerryI** [comment]
I am glad you like it, Jacopo :)

I totally agree with you on this topic. This is one of the reasons, why I started to develop web-based notebook interface. It is extremely slow and inconvenient to export/import stuff from OriginPro/Matlab/... to show to a college or digitize the data from an image just to get the data points from some published graph. 

We can definitely go much further.

Regarding the dynamics with sliders and animation or some other live-interactive things, it can already handle it within the browser, but requires some more development to make it more accessible and easy.

Hope your project will attract more people. May be on some later stages I will try to promote it in my university as part of a "data transparency" project.

Anyway, I will try to contribute from my side.

PS: Actually, in Adobe's specification on PDF/A it should support 3D graphics and scripts, but nobody supports it.

**Comment by jacopouggeri** [comment]
Alright! I integrated your contribution in the current main to serve as a demonstration. 
I have been busy with other stuff but I have worked a bit on this project this past week, since I'm working alone for now I'm having a bit of a hard time defining how to structure things and in which direction to go. For example, the current main handles citations with a manually defined partial in Hugo, with citations defined in YAML, but with the existence of citeproc-js and citation-js I think it would be best to let that be handled to pre made software that can also deal with bib files directly. 

I also found out about 11ty, which is a very customisable static site generator written in node.js. Since Fern doesn't need the whole machinery of Hugo, and Hugo allows for less customisability as it doesn't have plugins, I was considering switching to 11ty. For now, I have managed to partially integrate citation-js into 11ty.

I was also debating how fern could be distributed and how it could work. One way is as a CLI that hosts the file locally (like doing hugo server), although it is not very user friendly. Another could be as a website platform which allows anyone to upload a zip with the correct files to visualise their own article, which could be also packaged into an electron-js app to visualise files locally from a desktop app.

However, this also made me reflect that at this stage fern might be more about producing demos and results that can inspire discussion to, for example establish a standardised (and/or extensible) file/folder format for these sort of articles, which various platforms could then read in their own way, offering theming and layouts while is really all about how the content is packaged.

I had some conversations about PDFs and how they allow 3D figures, but as (I hope) you know, my plan for fern goes beyond the single feature, and in the direction of facilitating the integration of technology with article contents. My vision is that, in the future, it would also to allow for future technologies to be integrated and included too.

Anyway, I thank you once again for your contribution. Whenever you're available, you're always welcome to join in the discussion.

**Comment by jacopouggeri** [comment]
Alright! I integrated your contribution in the current main to serve as a demonstration. 
I have been busy with other stuff but I have worked a bit on this project this past week, since I'm working alone for now I'm having a bit of a hard time defining how to structure things and in which direction to go. For example, the current main handles citations with a manually defined partial in Hugo, with citations defined in YAML, but with the existence of citeproc-js and citation-js I think it would be best to let that be handled to pre made software that can also deal with bib files directly. 

I also found out about 11ty, which is a very customisable and lightweight static site generator written in node.js. Since Fern doesn't need the whole machinery of Hugo, and Hugo allows for less customisability as it doesn't have plugins, I was considering switching to 11ty. For now, I have managed to partially integrate citation-js into 11ty.

I was also debating how fern could be distributed and how it could work. One way is as a CLI that hosts the file locally (like doing hugo server), although it is not very user friendly. Another could be as a website platform which allows anyone to upload a zip with the correct files to visualise their own article, which could be also packaged into an electron-js app to visualise files locally from a desktop app.

However, this also made me reflect that at this stage fern might be more about producing demos and results that can inspire discussion to, for example, establish a standardised (and/or extensible) file/folder format for these sort of articles, which various platforms could then read in their own way, offering theming and layouts while is really all about how the content is packaged.

I had some conversations about PDFs and how they allow 3D figures, but as (I hope) you know, my plan for fern goes beyond the single feature, and in the direction of facilitating the integration of technology with article contents. My vision is that, in the future, it would also to allow for future technologies to be integrated and included too.

Anyway, I thank you once again for your contribution. Whenever you're available, you're always welcome to join in the discussion.

**Comment by jacopouggeri** [comment]
Alright! I integrated [your contribution](https://jacopouggeri.github.io/fern/wljs-test/) in the current main to serve as a demonstration. 
I have been busy with other stuff but I have worked a bit on this project this past week, since I'm working alone for now I'm having a bit of a hard time defining how to structure things and in which direction to go. For example, the current main handles citations with a manually defined partial in Hugo, with citations defined in YAML, but with the existence of citeproc-js and citation-js I think it would be best to let that be handled to pre made software that can also deal with bib files directly. 

I also found out about 11ty, which is a very customisable and lightweight static site generator written in node.js. Since Fern doesn't need the whole machinery of Hugo, and Hugo allows for less customisability as it doesn't have plugins, I was considering switching to 11ty. For now, I have managed to partially integrate citation-js into 11ty.

I was also debating how fern could be distributed and how it could work. One way is as a CLI that hosts the file locally (like doing hugo server), although it is not very user friendly. Another could be as a website platform which allows anyone to upload a zip with the correct files to visualise their own article, which could be also packaged into an electron-js app to visualise files locally from a desktop app.

However, this also made me reflect that at this stage fern might be more about producing demos and results that can inspire discussion to, for example, establish a standardised (and/or extensible) file/folder format for these sort of articles, which various platforms could then read in their own way, offering theming and layouts while is really all about how the content is packaged.

I had some people mention to me about PDFs and how they allow 3D figures, but as (I hope) you know, my plan for fern goes beyond the single feature, and in the direction of facilitating the integration of technology with article contents. My vision is that, in the future, it would also to allow for future technologies to be integrated and included too.

Anyway, I thank you once again for your contribution. Whenever you're available, you're always welcome to join in the discussion.

Cheers, Jacopo

**Pull request merged**
